apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-frontend
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-frontend
  template:
    metadata:
      labels:
        app: otel-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/open-telemetry/opentelemetry-demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://localhost:4317"
        - name: OTEL_SERVICE_NAME
          value: "otel-frontend"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=demo"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "https://dc.services.visualstudio.com/v2/track"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=e82bd70d-bc01-4e9f-bf63-af44bba4d188;IngestionEndpoint=https://australiaeast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://australiaeast.livediagnostics.monitor.azure.com/;ApplicationId=4cfb5ed0-ae9c-4a9b-ab42-102f1f0d7b95"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-frontend
  namespace: otel-demo
spec:
  selector:
    app: otel-frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
