apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-monitor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-monitor
  template:
    metadata:
      labels:
        app: otel-monitor
    spec:
      containers:
        - name: otel-monitor
          image: otel/opentelemetry-collector-contrib:latest
          env:
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: otel-monitor-secret
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
            - name: OTELCOL_CONFIG_FILE
              value: /conf/otel-collector-config.yaml
          volumeMounts:
            - name: config
              mountPath: /conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: otel-monitor-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-monitor
  namespace: monitoring
spec:
  selector:
    app: otel-monitor
  ports:
    - protocol: TCP
      port: 4317
      name: otlp-grpc
    - protocol: TCP
      port: 4318
      name: otlp-http
  type: ClusterIP
